#!/usr/bin/env node
/*
 * build-bank.js
 * -------------------------------------------------------------
 * Reads the human-readable question sources in /question-bank,
 * validates them, then compresses (deflate) + base64-encodes the
 * whole set into src/data/bank.generated.js.
 *
 * Only the generated (encoded) file is imported by the app, so the
 * readable source JSON never ends up in the shipped bundle. This
 * keeps the answer key out of the APK and shrinks the payload.
 *
 * Run with:  npm run build:bank
 */
const fs = require('fs');
const path = require('path');
const pako = require('pako');

const ROOT = path.resolve(__dirname, '..');
const SRC_DIR = path.join(ROOT, 'question-bank');
const OUT_FILE = path.join(ROOT, 'src', 'data', 'bank.generated.js');

// Keep in sync with src/data/categories.js
const VALID_CATEGORIES = new Set([
  'bangla', 'english', 'bd_affairs', 'intl_affairs', 'geography',
  'science', 'ict', 'math', 'mental', 'ethics',
]);

function loadSources() {
  if (!fs.existsSync(SRC_DIR)) {
    throw new Error(`Source folder not found: ${SRC_DIR}`);
  }
  const files = fs
    .readdirSync(SRC_DIR)
    .filter((f) => f.endsWith('.json'))
    .sort();
  if (files.length === 0) throw new Error('No .json source files found in question-bank/');

  let all = [];
  for (const file of files) {
    const full = path.join(SRC_DIR, file);
    let arr;
    try {
      arr = JSON.parse(fs.readFileSync(full, 'utf8'));
    } catch (e) {
      throw new Error(`Invalid JSON in ${file}: ${e.message}`);
    }
    if (!Array.isArray(arr)) throw new Error(`${file} must contain a JSON array`);
    console.log(`  • ${file}: ${arr.length} questions`);
    all = all.concat(arr);
  }
  return all;
}

function validate(questions) {
  const ids = new Set();
  const errors = [];
  const byCategory = {};

  questions.forEach((q, i) => {
    const where = `index ${i}${q && q.id ? ` (id=${q.id})` : ''}`;
    if (!q || typeof q !== 'object') return errors.push(`${where}: not an object`);
    if (!q.id) errors.push(`${where}: missing id`);
    else if (ids.has(q.id)) errors.push(`${where}: duplicate id`);
    ids.add(q.id);

    if (!VALID_CATEGORIES.has(q.categoryId)) errors.push(`${where}: unknown categoryId "${q.categoryId}"`);
    if (typeof q.question !== 'string' || !q.question.trim()) errors.push(`${where}: empty question`);
    if (!Array.isArray(q.options) || q.options.length !== 4) errors.push(`${where}: must have exactly 4 options`);
    else if (new Set(q.options).size !== 4) errors.push(`${where}: options must be distinct`);
    if (typeof q.answerIndex !== 'number' || q.answerIndex < 0 || q.answerIndex > 3) {
      errors.push(`${where}: answerIndex must be 0-3`);
    }

    byCategory[q.categoryId] = (byCategory[q.categoryId] || 0) + 1;
  });

  if (errors.length) {
    console.error('\nValidation failed:');
    errors.forEach((e) => console.error('  ✗ ' + e));
    throw new Error(`${errors.length} validation error(s)`);
  }
  return byCategory;
}

function encode(questions) {
  // Strip to only the fields the app needs, keeping the payload lean.
  const slim = questions.map((q) => ({
    id: q.id,
    categoryId: q.categoryId,
    question: q.question,
    options: q.options,
    answerIndex: q.answerIndex,
    explanation: q.explanation || '',
  }));
  const json = JSON.stringify(slim);
  const deflated = pako.deflate(json); // Uint8Array
  const b64 = Buffer.from(deflated).toString('base64');
  return { json, b64, rawBytes: Buffer.byteLength(json, 'utf8'), encBytes: b64.length };
}

function main() {
  console.log('Building question bank…');
  const questions = loadSources();
  const byCategory = validate(questions);
  const { b64, rawBytes, encBytes } = encode(questions);

  const banner =
    '// AUTO-GENERATED by scripts/build-bank.js — DO NOT EDIT BY HAND.\n' +
    '// Source of truth lives in /question-bank/*.json (not shipped in the bundle).\n' +
    `// ${questions.length} questions. Regenerate with: npm run build:bank\n`;
  const body = `export const ENCODED_BANK =\n  '${b64}';\n`;

  fs.writeFileSync(OUT_FILE, banner + body, 'utf8');

  const pct = ((1 - encBytes / rawBytes) * 100).toFixed(1);
  console.log('\nCategory breakdown:');
  Object.entries(byCategory)
    .sort()
    .forEach(([c, n]) => console.log(`  ${c.padEnd(14)} ${n}`));
  console.log(
    `\n✓ Wrote ${path.relative(ROOT, OUT_FILE)}\n` +
      `  ${questions.length} questions | raw JSON ${(rawBytes / 1024).toFixed(1)} KB ` +
      `→ encoded ${(encBytes / 1024).toFixed(1)} KB (${pct}% smaller)`
  );
}

main();
